model_name: VBD

# Data Config
train_data_path: /u/zixuz/vbd/data_extract/training_processed
val_data_path:  /u/zixuz/vbd/data_extract/validation_processed
anchor_path: /u/zixuz/vbd/diffusion_waymax/vbd/data/cluster_64_center_dict.pkl
log_dir: /u/zixuz/vbd/ablation_results


# Wandb Config
use_wandb: True
username: zzx9636
project: VBD

# Checkpoint Config
init_from: null

# Model Config
agents_len: 32
future_len: 80
action_len: 2
encoder_layers: 6
prediction_type: sample
encoder_version: v2

# Diffusion Params
diffusion_steps: 50
schedule_type: cosine
schedule_s: 0
schedule_e: 1
schedule_tau: 1

action_mean: [0.0, 0.0]
action_std: [1.0, 0.15]
clamp_value: 5.0

# Training Params
batch_size: 12
num_workers: 8
lr: 0.0002
weight_decay: 0.01
epochs: 20
lr_warmup_step: 5000
lr_step_freq: 1000
lr_step_gamma: 0.98

train_encoder: True
train_denoiser: True
train_predictor: True

encoder_ckpt: null
